package iuh.network;

public enum CommandType {
    XAC_THUC_TAI_KHOAN,
    GET_ROOM_BY_ID,
    GET_ALL_ROOMS,
    GET_ALL_TANG,
    GET_ALL_LOAI_PHONG,
    GET_ROOMS_BY_KEYWORD,

    CREATE_PHONG,

    UPDATE_PHONG,

    DELETE_PHONG,

    // ===== ĐẶT PHÒNG =====
    GET_PHONG_TRONG,
    LAY_MA_PHIEU_DAT_PHONG,
    DAT_PHONG,
    TIM_KHACH_HANG_CCCD,
    THEM_KHACH_HANG,
    CAP_NHAT_KHACH_HANG,
    PHAT_SINH_MA_KHACH_HANG,
    GET_ALL_KHACH_HANG,
    TIM_KHACH_HANG_THEO_KEYWORD,
    XOA_KHACH_HANG_MA,

    // ===== THỐNG KÊ =====
    LAY_THONG_KE,

    // ===== KHUYẾN MÃI =====
    GET_ALL_KHUYEN_MAI,
    GET_KHUYEN_MAI_BY_ID,
    GET_KHUYEN_MAI_BY_KEYWORD,
    CREATE_KHUYEN_MAI,
    UPDATE_KHUYEN_MAI,
    DELETE_KHUYEN_MAI,
    PHAT_SINH_MA_KHUYEN_MAI,

    // ===== CA LÀM VIỆC NHÂN VIÊN =====
    GET_ACTIVE_SHIFT,
    MO_CA,
    KET_CA,
    GET_SHIFT_HISTORY,
    GET_ALL_CA,

    // Thanh Toán pannel
    GET_DANH_SACH_DE_THANH_TOAN,
    CO_THE_THANH_TOAN,
    THANH_TOAN,
    GET_DANH_SACH_KHUYEN_MAI_HOP_LE,
    TIEN_SAU_KHI_AP_GIAM_GIA,

    // ==== HỦY PHÒNG ====
    GET_DS_PHONG_DE_HUY,
    HUY_PHONG,
    // ========NHÂN VIÊN=============
    GET_ALL_NHAN_VIEN,
    SEARCH_NHAN_VIEN,
    GET_NHAN_VIEN_BY_ID,
    ADD_NHAN_VIEN_AUTO_CODE,
    TAO_MAT_KHAU_MAC_DINH,
    DELETE_NHAN_VIEN,
    UPDATE_NHAN_VIEN,
    GENERATE_NEXT_MA_NHAN_VIEN,
    DOI_MAT_KHAU,
    LAY_MAT_KHAU_HIEN_TAI,

    // ========ĐỔI PHÒNG======
    GET_AVAILABLE_ROOMS,
    GET_ALL_BOOKED_ROOMS,
    GET_MA_PDP_BY_PHONG,
    DOI_PHONG,

    // ============GIA HẠN PHÒNG========
    TIM_PHONG_DANG_THUE,
    IS_ROOM_AVAILABLE_FOR_EXTENSION,
    GIA_HAN_NHIEU,

    // ======= Quản lý hóa đơn ========
    GET_ALL_HOA_DON,
    SEARCH_HOA_DON,

    GET_DANH_SACH_PHONG_DE_NHAN,
    NHAN_PHONG,

    //=======PHIẾU ĐỔI PHÒNG====
    GET_ALL
}
